name: Trigger on PR

on:
  pull_request:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    uses: ./.github/workflows/build-image.yaml
    secrets: inherit
